CREATE TABLE IF NOT EXISTS mcp_servers (
    key VARCHAR(250) NOT NULL PRIMARY KEY,
    value JSONB NOT NULL,
    tenant_id VARCHAR(250) GENERATED ALWAYS AS (value ->> 'tenantId') STORED,
    enabled BOOL NOT NULL GENERATED ALWAYS AS (CAST(value ->> 'enabled' AS BOOL)) STORED,
    server_name VARCHAR(250) GENERATED ALWAYS AS (value ->> 'serverName') STORED,
    created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS mcp_servers_tenant ON mcp_servers ("tenant_id");

CREATE OR REPLACE TRIGGER mcp_servers_updated BEFORE UPDATE
    ON mcp_servers FOR EACH ROW EXECUTE PROCEDURE
    UPDATE_UPDATED_DATETIME();
